apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the component (AKA endpoints).
  inbound:
    # +required Unique name for the endpoint. (This name will be used when generating the managed API)
    - name: appointments
      # +required Numeric port value that gets exposed via the endpoint
      port: 8080
      # +required Type of traffic that the endpoint is accepting. For example: REST, GraphQL, etc.
      # Allowed values: REST, GraphQL, GRPC, TCP, UDP.
      type: REST
      # +optional Network level visibility of the endpoint. Defaults to Public
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # +optional Context (base path) of the API that gets exposed via the endpoint.
      # This is mandatory if the endpoint type is set to REST or GraphQL.
      context: /
      # +optional The path to the schema definition file. Defaults to wildcard route if not specified.
      # This is only applicable to REST endpoint types.
      # The path should be relative to the Docker context.
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///codechallenge/appointment-management/cmrqnc/8b1c3/v1.0/ORGANIZATION
      connectionConfig: 01eef67c-b6e6-17c0-9120-68782ddbb0c9
      env:
      - from: ServiceURL
        to: APPOINTMENT_SERVICE_URL
      - from: ConsumerKey
        to: APPOINTMENTS_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to: APPOINTMENTS_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: APPOINTMENTS_OAUTH_TOKEN_URL
